# Generated by Django 3.1.7 on 2021-05-29 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='role',
            field=models.CharField(default='ROLE_USER', max_length=100),
        ),
        migrations.AddField(
            model_name='account',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
