# Generated by Django 3.2.3 on 2021-05-31 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='author',
        ),
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='material',
        ),
        migrations.RemoveField(
            model_name='product',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='product',
            name='types',
        ),
        migrations.CreateModel(
            name='Electronic',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.product')),
                ('supplier', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='shop.supplier')),
                ('types', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='shop.types')),
            ],
            bases=('shop.product',),
        ),
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.product')),
                ('brand', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='shop.brand')),
                ('material', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='shop.material')),
            ],
            bases=('shop.product',),
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.product')),
                ('author', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='shop.author')),
                ('category', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='shop.category')),
            ],
            bases=('shop.product',),
        ),
    ]
