# Generated by Django 3.2.3 on 2021-06-01 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_itemincart_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
    ]
